# Generated by Django 3.2.8 on 2021-10-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, verbose_name='Номер телефона'),
        ),
    ]
