# Generated by Django 3.2.8 on 2021-10-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.DecimalField(decimal_places=20, max_digits=25, null=True, verbose_name='Номер телефона'),
        ),
    ]
