# Generated by Django 3.2.8 on 2021-10-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_big',
            field=models.BooleanField(default=False, verbose_name='описание?'),
        ),
        migrations.AddField(
            model_name='maintype',
            name='typeslug',
            field=models.CharField(max_length=200, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductAvt',
            field=models.ImageField(blank=True, default='media/NoImageAvailable.png', upload_to='media/productsAvt/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductMain',
            field=models.ImageField(blank=True, default='media/NoImageAvailable.png', upload_to='media/products/'),
        ),
    ]
