# Generated by Django 3.2.8 on 2021-10-28 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211028_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaTypeFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200, unique=True, verbose_name='аромат чая')),
                ('slug', models.CharField(max_length=400, verbose_name='url')),
            ],
            options={
                'verbose_name': 'категория (аромат чая)',
                'verbose_name_plural': 'Категории (аромат чая)',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='TeaType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.teatype', verbose_name='тип/вид чая'),
        ),
        migrations.AddField(
            model_name='product',
            name='TeaTypeFavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.teatypefavor', verbose_name='аромат чая'),
        ),
    ]
