# Generated by Django 3.2.8 on 2021-10-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211028_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='TeaType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tea_type', to='catalog.teatype', verbose_name='тип/вид чая'),
        ),
        migrations.AlterField(
            model_name='product',
            name='TeaTypeFavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_favor', to='catalog.teatypefavor', verbose_name='аромат чая'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='catalog.country', verbose_name='страна производитель'),
        ),
    ]
