# Generated by Django 3.2.8 on 2021-10-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211030_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default='собственное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.manufacturer', verbose_name='производитель'),
        ),
    ]
